
const movie_data = {
    data: [
        {
            key: 1,
            title: "El padre",
            originaltitle: "The Father",
            synopsis: "Anthony (Anthony Hopkins), un hombre de 80 años mordaz, algo travieso y que tercamente ha decidido vivir solo, rechaza todos y cada uno de las cuidadoras que su hija Anne (Olivia Colman) intenta contratar para que le ayuden en casa. Está desesperada porque ya no puede visitarle a diario y siente que la mente de su padre empieza a fallar y se desconecta cada vez más de la realidad. Anne sufre la paulatina pérdida de su padre a medida que la mente de éste se deteriora, pero también se aferra al derecho a vivir su propia vida.",
            duration: 97,
            country: "Reino Unido",
            director: "Florian Zeller",
            script: "Florian Zeller, Christopher Hampton",
            music: "Ludovico Einaudi",
            photography: "Ben Smithard",
            distribution: "Anthony Hopkins, Olivia Colman, Imogen Poots, Rufus Sewell, Olivia Williams, Mark Gatiss, Evie Wray, Ayesha Dharker",
            producer: "Trademark Films / Embankment Films / Film4 Productions / F Comme Film / AG Studios NYC",
            gender: "Drama",
            img:"https://firebasestorage.googleapis.com/v0/b/oscars-a57ef.appspot.com/o/cover%2Fthe_father.jpg?alt=media&token=e5c96700-16c6-4d34-92ff-2a5eb76c4e33",
            votes:15,
        },
        {
            key: 2,
            title: "Judas y el mesías negro",
            originaltitle: "Judas and the Black Messiah",
            synopsis: "Historia real que gira en torno a Bill, un delincuente que se dedica a robar coches y al que, tras ser detenido, el FBI le propone la absolución de sus delitos si coopera con ellos infiltrándose en el partido \"\"Panteras Negras\"\", del líder y activista negro Fred Hampton.",
            duration: 126,
            country: "Estados Unidos",
            director: "Shaka King",
            script: "Shaka King, Will Berson",
            music: "Craig Harris, Mark Isham",
            photography: "Sean Bobbitt",
            distribution: "Daniel Kaluuya, Lakeith Stanfield, Jesse Plemons, Martin Sheen, Ashton Sanders, Lil Rel Howery, Algee Smith, Jermaine Fowler, Robert Longstreet, Terayle Hill, Dominique Fishback, Nick Fink, Darrell Britt-Gibson, Amber Chardae Robinson, Adam Ratcliffe, Caleb Eberhardt, Zak Lee, Alysia Joy Powell, Crystal Lee Brown, Amari Cheatom, Debbie Scaletta, Chris Hahn, Michael Buonomo, James Udom, Michael Harrity, Matt Hudson, Linda D Gaines, Alonda Shevette, Steve Rizzo, Laura Allen, David Gragg, Peter Lawson Jones, Mell Bowser, David Haynes, Aaron Kleiber, Tone Tank, Roger Petan, Todd C. Adelman, Anthony Garcia, Chris Drexel, Shalanda Fresh, Chris Breen, Bobby Rodriguez, Chris McCail, Brian Andrus, Suzie Coker, Logan Fry, David Goebel, Dominique Thorne",
            producer: "Bron Creative / MACRO / Participant Media",
            gender: "Drama",
            img:"https://firebasestorage.googleapis.com/v0/b/oscars-a57ef.appspot.com/o/cover%2Fjudas_and_the_black_messiah.jpg?alt=media&token=d421e802-8594-42ee-9659-fc3c38fec18f",
            votes:15,
        },

        {
            key: 3,
            title: "Mank",
            originaltitle: "Mank",
            synopsis: "Biopic sobre Herman Mankiewicz, guionista de 'Ciudadano Kane', que repasa el proceso de rodaje de la obra maestra de Orson Welles, dirigida y estrenada en 1941. La película toma como base un guión escrito por Jack Fincher, padre de David Fincher, antes de morir en 2003",
            duration: 132,
            country: "Estados Unidos",
            director: "David Fincher",
            script: "Jack Finche",
            music: "Trent Reznor, Atticus Ross",
            photography: "Erik Messerschmidt",
            distribution: "Gary Oldman, Amanda Seyfried, Arliss Howard, Charles Dance, Tom Burke, Lily Collins, Tuppence Middleton, Tom Pelphrey, Ferdinand Kingsley, Jamie McShane, Joseph Cross, Sam Troughton, Toby Leonard Moore, Leven Rambin, Madison West, Adam Shapiro, Monika Gossmann, Paul Fox, Jessie Cohen, Amie Farrell, Alex Leontev, Stewart Skelton, Craig Robert Young, Derek Petropolis, Jaclyn Bethany, Arlo Mertz",
            producer: "Netflix",
            gender: "Drama/Comedia",
            img:"https://firebasestorage.googleapis.com/v0/b/oscars-a57ef.appspot.com/o/cover%2FMank.jpg?alt=media&token=e1fe9a7e-c647-492c-b6c1-8f953728a365",
            votes:15,
        },

        {
            key: 4,
            title: "Minari. Historia de mi familia",
            originaltitle: "Minari",
            synopsis: "David, un niño coreano-americano de 7 años, ve cómo a mediados de los años 80 su vida cambia, de la noche a la mañana, cuando su padre decide mudarse junto a toda su familia a una zona rural de Arkansas para abrir allí una granja, con el propósito de lograr alcanzar el sueño americano.",
            duration: 115,
            country: "Estados Unidos",
            director: "Lee Isaac Chung",
            script: "Lee Isaac Chung",
            music: "Emile Mosseri",
            photography: "Lachlan Milne",
            distribution: "Steven Yeun, Han Ye-ri, Youn Yuh-jung, Alan S. Kim, Noel Cho, Will Patton, Scott Haze, Eric Starkey, Esther Moon, Tina Parker, Darryl Cox",
            producer: "Plan B Entertainment",
            gender: "Drama",
            img:"https://firebasestorage.googleapis.com/v0/b/oscars-a57ef.appspot.com/o/cover%2FMinari.jpg?alt=media&token=4e1e265d-3d98-4b68-9a4a-80494c15eaba",
            votes:15,
        },
        {
            key: 5,
            title: "Nomadland",
            originaltitle: "Nomadland",
            synopsis: "Una mujer, después de perderlo todo durante la recesión, se embarca en un viaje hacia el Oeste americano viviendo como una nómada en una caravana. Tras el colapso económico que afectó también a su ciudad en la zona rural de Nevada, Fern toma su camioneta y se pone en camino para explorar una vida fuera de la sociedad convencional, como nómada",
            duration: 108,
            country: "Estados Unidos",
            director: "Chloé Zhao",
            script: "Chloé Zhao",
            music: "Ludovico Einaudi",
            photography: "Joshua James Richards",
            distribution: "Frances McDormand, David Strathairn, Linda May, Charlene Swankie, Bob Wells, Gay DeForest, Patricia Grier",
            producer: "Highwayman Films / Cor Cordium Productions / Hear/Say Productions",
            gender: "Drama",
            img: "https://firebasestorage.googleapis.com/v0/b/oscars-a57ef.appspot.com/o/cover%2FNomadland.jpg?alt=media&token=a219e63d-d808-4b9f-96c4-09ec4ff0cadf",
            votes:15,
        },

        {
            key: 6,
            title: "Una joven prometedora",
            originaltitle: "Promising Young Woman",
            synopsis: "Cassie tenía un brillante futuro por delante hasta que un desagradable incidente truncó su carrera. Ahora nada en su vida es lo que parece: es inteligente, audaz y vive una doble vida de noche. Cassie tiene la oportunidad de enmendar todo lo que no salió bien en su pasado... vengándose de los culpables.",
            duration: 113,
            country: "Reino Unido",
            director: "Emerald Fennell",
            script: "Emerald Fennell",
            music: "Anthony B. Willis",
            photography: "Benjamin Kracun",
            distribution: "Carey Mulligan, Bo Burnham, Alison Brie, Connie Britton, Jennifer Coolidge, Adam Brody, Laverne Cox, Clancy Brown, Angela Zhou, Christopher Mintz-Plasse, Alfred Molina, Molly Shannon, Sam Richardson, Steve Monroe, Casey Adams",
            producer: "Filmnation Entertainment / Focus Features / LuckyChap Entertainment",
            gender: "Thriller / Drama / Comedia",
            img:"https://firebasestorage.googleapis.com/v0/b/oscars-a57ef.appspot.com/o/cover%2Fpromising_young_woman.jpg?alt=media&token=2c8a14b6-b593-4064-b6c2-e1c1fa64f7df",
            votes:15,
        },

        {
            key: 7,
            title: "Sound of Metal",
            originaltitle: "Sound of Metal",
            synopsis: "Narra la historia de un joven batería de una banda de música que comienza a perder la audición.",
            duration: 120,
            country: "Estados Unidos",
            director: "Darius Marder",
            script: "Darius Marder, Abraham Marder",
            music: "Nicolas Becker, Abraham Marder",
            photography: "Daniel Bouquet",
            distribution: "Riz Ahmed, Olivia Cooke, Paul Raci, Mathieu Amalric, Tom Kemp, Bill Thorpe, William Xifaras, David Arthur Sousa, Michael Tow, Marisa Defranco, Lauren Ridloff, Jamie Ghazarian, Chris Perfetti, Hillary Baack, Chelsea Bond",
            producer: "Caviar Films",
            gender: "Drama",
            img:"https://firebasestorage.googleapis.com/v0/b/oscars-a57ef.appspot.com/o/cover%2FSound%20of%20Metal.jpg?alt=media&token=f5662fe0-2f48-4629-af05-5b1c0b0a216d",
            votes:15,
        },

        {
            key: 8,
            title: "El juicio de los 7 de Chicago",
            originaltitle: "The Trial of the Chicago 7",
            synopsis: "En 1969 se celebró uno de los juicios más populares de la Historia de Estados Unidos, en el que siete individuos detenidos durante una manifestación en contra de la guerra de Vietnam fueron juzgados tras ser acusados de conspirar en contra de la seguridad nacional. Su arresto se produjo a consecuencia de unos disturbios contra la policía y el juicio, impulsado por el nuevo fiscal general, fue claramente político, dando lugar a una serie de conflictos sociales -manifestaciones, movimientos ciudadanos, impulso de los derechos civiles- que pasarían a la posteridad en una época de grandes cambios en los Estados Unidos.",
            duration: 129,
            country: "Estados Unidos",
            director: "Aaron Sorkin",
            script: "Aaron Sorkin",
            music: "Daniel Pemberton",
            photography: "Phedon Papamichael",
            distribution: "Eddie Redmayne, Sacha Baron Cohen, Mark Rylance, Frank Langella, Joseph Gordon-Levitt, Jeremy Strong, John Carroll Lynch, Alex Sharp, Yahya Abdul-Mateen II, Michael Keaton, Ben Shenkman, J.C. MacKenzie, Noah Robbins, Alice Kremelberg, Danny Flaherty, John Doman, Mike Geraghty, Kelvin Harrison Jr., Caitlin Fitzgerald, John Quilty, Max Adler, Wayne Duvall, Damian Young, C.J. Wilson",
            producer: "Amblin Partners / Paramount Pictures / Cross Creek Pictures / Marc Platt Productions / Reliance Entertainment / DreamWorks SKG / MadRiver Pictures / S",
            gender: "Drama",
            img: "https://firebasestorage.googleapis.com/v0/b/oscars-a57ef.appspot.com/o/cover%2Fthe_trial_of_the_chigaco_7.jpg?alt=media&token=877a567a-a7d1-4f02-8e7a-36cda789b37d",
            votes:15,
        },


    ]
}
export default movie_data

